### ISSUE TITLE
USER STORY: Editing and Deleting Polls as an Administrator

### ISSUE THREAD

**Issue by xttrust** [xttrust/love-running#3]
In order to **maintain the accuracy of polls and keep the platform up-to-date** as a **administrator**, I can **edit and delete existing polls.**

# Acceptance Criteria

- The administrator should have access to a list of all existing polls.
- The administrator should be able to select a poll from the list and choose to edit its question, options, or delete it entirely.

# Tasks

- [ ] Implement a UI component to display a list of existing polls.
- [ ] Create functionality for the administrator to edit the question, options, and other details of a selected poll.
- [ ] Implement a mechanism to allow the administrator to delete a poll from the list.
